"""add_refresh_token_hash_to_users

Revision ID: aed50e10bb9b
Revises: 7747f1da2a72
Create Date: 2026-03-15 15:12:13.743616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed50e10bb9b'
down_revision: Union[str, Sequence[str], None] = '7747f1da2a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
